-- 코드를 작성해주세요

SELECT ID, IF(B.LOCAL_COUNT IS NULL, 0, LOCAL_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN (

        SELECT PARENT_ID, COUNT(*) AS LOCAL_COUNT
        FROM ECOLI_DATA
        GROUP BY PARENT_ID
) B ON A.ID = B.PARENT_ID


