-- 코드를 작성해주세요

WITH Q AS (
    SELECT 
        MONTH(DIFFERENTIATION_DATE) AS MONTH,
        CASE
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
            ELSE '4Q'
        END AS QUARTER
    FROM ECOLI_DATA
)

SELECT Q.QUARTER AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM Q
GROUP BY Q.QUARTER
ORDER BY Q.QUARTER