-- 코드를 입력하세요

SET @MEMBER_ID = (
SELECT B.MEMBER_ID
FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
GROUP BY B.MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1
);

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = @MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT