-- 코드를 작성해주세요
SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM SKILLCODES A 
JOIN DEVELOPERS B ON (B.SKILL_CODE & A.CODE) IN (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)
ORDER BY ID 