-- 코드를 작성해주세요

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, B.M - A.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A JOIN (
                        SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS M
                        FROM ECOLI_DATA
                        GROUP BY YEAR(DIFFERENTIATION_DATE)
                        ) B ON YEAR(A.DIFFERENTIATION_DATE) = B.Y

ORDER BY YEAR, YEAR_DEV