-- 코드를 입력하세요
# SELECT B.HISTORY_ID, DISTINCT(A.CAR_ID), B.START_DATE, B.END_DATE
SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE MONTH(START_DATE) = 10 AND CAR_TYPE = '세단'
ORDER BY B.CAR_ID DESC